### ISSUE TITLE
New Style Idea: No Gap Columns

### ISSUE THREAD

**Issue by mrwweb** [mrwweb/useful-block-styles#10]
Columns have margins in between them by default. We could remove them so that the contents of columns directly abut each other, allowing for things like cool adjacent blocks of color (coming from Group blocks or...maybe someday...column block background colors).

Questions:

1. Do 90%+ sites need this style?

**Comment by rtvenge** [comment]
@mrwweb do you have an example of this? My concern is that if you apply this style, at some point, padding needs to be added to content inside the column and this would add complexity and possibly setup editors for failure by having text run together.

At first glance, I don't think 90% of sites would need this but I could be persuaded with an example. 😄

**Comment by mrwweb** [comment]
@rtvenge My assumption is that the padding would then come from the elements with backgrounds, but I think you've already convinced me this one is too niche.

**Comment by mrwweb** [comment]
Emerging guidelines for this plugin: "stick to styles that are useful utility classes (small, single purpose) and mostly for Text blocks."

Therefore, closing this issue.
