### ISSUE TITLE
New Style Idea: Full-height Column Contents

### ISSUE THREAD

**Issue by mrwweb** [mrwweb/useful-block-styles#11]
The idea is that you make columns flex box parents in the column direction and stretch all containers blocks (except media) to fill any remaining space. This way, paragraph or group blocks with backgrounds will always fill the entirety of both columns, creating a nice masonry-esque alignment.

Is this a style that makes sense on 90%+ of sites?

**Comment by rtvenge** [comment]
One thing to think about is how nested columns work with this. We'd just want to test that to ensure it works as expected and they don't flow in column direction. 😄

**Comment by mrwweb** [comment]
Emerging guidelines for this plugin: "stick to styles that are useful utility classes (small, single purpose) and mostly for Text blocks."

Therefore, closing this issue.
