### ISSUE TITLE
New Style Idea: Screen Reader Text for Headings

### ISSUE THREAD

**Issue by mrwweb** [mrwweb/useful-block-styles#14]
It's not uncommon that a complex page layout would be improved by screen reader text headings.

I'd propose adding an `.is-screen-reader-text` style that is just a copy of the standard, recommended `.screen-reader-text` class for WP.

I think I only envision this being useful for headings, but interested in other ideas.

**Comment by mrwweb** [comment]
In terms of other implementations of this idea, I've build this feature before, but also ran across it in the [Michelle theme](https://webmandesign.github.io/docs/michelle/#css-classes) last week. It's a nice implementation that grays out the heading and adds an icon in the editor.

**Comment by rtvenge** [comment]
@mrwweb I feel like I would use this at some point. Sounds like a great idea!

**Comment by mrwweb** [comment]
@rtvenge Sweet. I'll try to get a PR in this week.
