### ISSUE TITLE
New Style Idea: Grid Group

### ISSUE THREAD

**Issue by mrwweb** [mrwweb/useful-block-styles#8]
This idea is for a much more aggressive layout style, unlike all the existing typography-focused ones, so I'm a little hesitant to add it. It might even be better as a different plugin.

The idea: use CSS grid to provide 2, 3, and 4 column layouts for any blocks put into a grid with that style. I think it could be done really nicely with only CSS styles, though some care would have to be taken to make sure that things like images and embeds are resized correctly.

My biggest question is whether this passes the "90%+ of sites need this" rule.

**Comment by rtvenge** [comment]
@mrwweb Putting my critical cap on 😄: What would this give us that columns (or equal height columns) give us? Would it be multiple rows? Anything else?

If I have a complex layout, I generally make a custom block but maybe thats because the current columns don't cut it. 😄

Do you have an example of where this would be a good fit? I'm thinking maybe a [3-up/multi-row card layout](https://develop-carlton-landing.pantheonsite.io/ownership/#guild)?

**Comment by mrwweb** [comment]
> What would this give us that columns (or equal height columns) give us?

Better wrapping and multiple rows. [Here's a page](https://wscadv.org/staff/) I built with that technique. Very similar to your link.

Example two 3-column blocks make a 3x2 grid but can't wrap to a 2x3 grid.

**Comment by rtvenge** [comment]
@mrwweb it looks like your example is very similar to mine. I'm sold. I use something like this on almost every site.

**Comment by mrwweb** [comment]
@rtvenge I was thinking about this on my dog walk this morning. I wonder if it's possible to create a standalone plugin for the [Block Directory](https://wordpress.org/support/article/block-directory/) with this as a style or block variation. That would be an awesome tool to install only when you need it, and would then be available through the block library installer.

After all our conversations and talking through the different block ideas, it feels like maybe this plugin should really stick to styles for text blocks rather than branching out into layout. (Maybe the buttons at bottom block is an exception? #9)

**Comment by rtvenge** [comment]
@mrwweb Good idea to keep a scope to this. I like a line in the sand on this so we don't get carried away. 😄 

If you add to the Block Directory, is it a totally new plugin or does it live in this plugin but is a net-new block?

**Comment by mrwweb** [comment]
@rtvenge It would definitely have to be a nice plugin, but it's a little unclear if it could be [included in the block directory](https://github.com/WordPress/wporg-plugin-guidelines/blob/block-guidelines/blocks.md). I think it should qualify, but it clearly doesn't meet the standards because it's not a separate block. I [opened a ticket](https://github.com/WordPress/wporg-plugin-guidelines/issues/74) asking for clarification.

**Comment by mrwweb** [comment]
I think we've basically decided to stick to styles that are useful utility classes (small, single purpose) and mostly for Text blocks. I still think this thing should happen, just as a separate plugin. Closing for now.
